import { Inter, Domine } from '@next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });
const domine = Domine({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body className={`${inter.className} ${domine.className}`}>
      {children}
      </body>
      </html>
  );
}
